language: node_js
node_js:
  - "10"
addons:
  chrome: stable
install:
  - yarn
jobs:
  include:
    - stage: test
      name: "Lint"
      script: yarn lint
    - script: yarn test-ci
      name: "Test"
